version: '3.1'

services:
  microblog:
    container_name: microblog
    image: microblog
    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - 6565:80
networks:
  default:
    external:
      name: server_default
